# $Id: Makefile,v 1.1 2006/02/14 21:13:11 sayer Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=nathelper.so
LIBS=

include ../../Makefile.modules
